-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "isBlocked" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "blockedReason" TEXT,
ADD COLUMN IF NOT EXISTS "blockedAt" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Transaction" ADD COLUMN IF NOT EXISTS "paidPrice" TEXT,
ADD COLUMN IF NOT EXISTS "receiptUrl" TEXT,
ADD COLUMN IF NOT EXISTS "payerName" TEXT,
ADD COLUMN IF NOT EXISTS "payerPhone" TEXT,
ADD COLUMN IF NOT EXISTS "payerEmail" TEXT;

ALTER TABLE "Job" ALTER COLUMN "coinCost" SET DEFAULT 1;
